name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    if: "!contains(github.event.head_commit.message, '--skipci')"
    runs-on: ubuntu-latest
    container:
      image: golang:1.23-bookworm
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        go build -buildvcs=false -o bin/findtfvars ./cmd/findtfvars
        go build -buildvcs=false -o bin/tfvars-to-args ./cmd/tfvars-to-args
    - name: Test
      run: go test ./...
    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tfvars-tools
        path: bin/

  release:
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}